---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages('xtable')
library(readxl)
library(dplyr)
library(tmap)
library(tmaptools)
library(sf)
library(ca)
library(xtable)
```

```{r}
wyniki <- read.csv('wyniki_gl_na_listy_po_obwodach_sejm.csv', sep= ';')
wyniki <- wyniki %>% 
  select(1, 2, 32:42)
names(wyniki) <- c('symbol', 'TERYT', 'wyborcy', 'ko', 'emeryci', 'konf', 'psl', 'prawica', 'pis', 'liroy', 'sld', 'bis', 'niemcy')
```

```{r}
# zdobywca mandatu w okregu
mandat1 <- function() {
  if (konf == max(konf, pis, ko, emeryci, niemcy, psl, liroy, sld, bis, prawica, na.rm = TRUE)) {
    return("konf")
  } else if (pis == max(konf, pis, ko, emeryci, niemcy, psl, liroy, sld, bis, prawica, na.rm = TRUE)) {
    return("pis")
  } else if (ko == max(konf, pis, ko, emeryci, niemcy, psl, liroy, sld, bis, prawica, na.rm = TRUE)) {
    return("ko")
  } else if (emeryci == max(konf, pis, ko, emeryci, niemcy, psl, liroy, sld, bis, prawica, na.rm = TRUE)) {
    return("emeryci")
  } else if (niemcy == max(konf, pis, ko, emeryci, niemcy, psl, liroy, sld, bis, prawica, na.rm = TRUE)) {
    return("niemcy")
  } else if (psl == max(konf, pis, ko, emeryci, niemcy, psl, liroy, sld, bis, prawica, na.rm = TRUE)) {
    return("psl")
  } else if (liroy == max(konf, pis, ko, emeryci, niemcy, psl, liroy, sld, bis, prawica, na.rm = TRUE)) {
    return("liroy")
  } else if (sld == max(konf, pis, ko, emeryci, niemcy, psl, liroy, sld, bis, prawica, na.rm = TRUE)) {
    return("sld")
  } else if (bis == max(konf, pis, ko, emeryci, niemcy, psl, liroy, sld, bis, prawica, na.rm = TRUE)) {
    return("bis")
  } else if (prawica == max(konf, pis, ko, emeryci, niemcy, psl, liroy, sld, bis, prawica, na.rm = TRUE)) {
    return("prawica")
  } else{
    return(0)
  }
}

mandat2 <- function() {
  if(blok_lewo == max(blok_lewo, blok_prawo, na.rm=TRUE)) {
    return("blok_lewo")
  } else if(blok_prawo == max(blok_lewo, blok_prawo, na.rm = TRUE)) {
    return("blok_prawo")
  } else {
    return(0)
  }
}

```

```{r}
dfo <- data.frame(okreg=integer(),
                  wyborcy=integer())

for (x in 1:460) {
  okreg <- read_excel(path = 'nowe_jow.xlsx', sheet = x)
  okreg <- left_join(okreg, wyniki, by = 'symbol')
  
  wyborcy <- as.numeric(okreg$wyborcy)
  wyborcy <- sum(wyborcy, na.rm = TRUE)
  
    dfo_temp <- data.frame(x, wyborcy)
  names(dfo_temp) <- c("okreg", "wyborcy")
  dfo <- rbind(dfo, dfo_temp)
}

```


```{r}
# scenariusz I
df1 <- data.frame(okreg=integer(),
                  teryt=integer(),
                  konf = integer(),
                  pis = integer(),
                  ko = integer(),
                  emeryci = integer(),
                  niemcy = integer(),
                  psl = integer(),
                  liroy=integer(),
                  sld=integer(),
                  bis=integer(),
                  prawica=integer(),
                  mandat=character())


for(x in 1:460){
  okreg <- read_excel(path = 'nowe_jow.xlsx', sheet = x)
  okreg <- left_join(okreg, wyniki, by = 'symbol')
  
  teryt <- as.numeric(substr((okreg$TERYT), 1, 2))
  teryt <- mean(teryt)
  
  konf <- as.numeric(okreg$konf)
  konf <- sum(konf, na.rm = TRUE)
  
  pis <- as.numeric(okreg$pis)
  pis <- sum(pis, na.rm = TRUE)
  
  ko <- as.numeric(okreg$ko)
  ko <- sum(ko, na.rm = TRUE)
  
  emeryci <- as.numeric(okreg$emeryci)
  emeryci <- sum(emeryci, na.rm = TRUE)
  
  niemcy <- as.numeric(okreg$niemcy)
  niemcy <- sum(niemcy, na.rm = TRUE)
  
  psl <- as.numeric(okreg$psl)
  psl <- sum(psl, na.rm = TRUE)

  liroy <- as.numeric(okreg$liroy)
  liroy <- sum(liroy, na.rm = TRUE)
  
  sld <- as.numeric(okreg$sld)
  sld <- sum(sld, na.rm = TRUE)
  
  bis <- as.numeric(okreg$bis)
  bis <- sum(bis, na.rm = TRUE)
  
  prawica <- as.numeric(okreg$prawica)
  prawica <- sum(prawica, na.rm = TRUE)
  
  df1_temp <- data.frame(x, teryt, konf, pis, ko, emeryci, niemcy, psl, liroy, sld, bis, prawica, mandat1())
  names(df1_temp) <- c("okreg", "teryt", "konf", "pis", "ko", "emeryci", "niemcy", "psl", "liroy", "sld", "bis", "prawica", "mandat")
  df1 <- rbind(df1, df1_temp)
  
}
table(df1$mandat)

```

```{r}
# scenariusz II

df2 <- data.frame(okreg=integer(),
                  teryt=integer(),
                  blok_lewo=integer(),
                  blok_prawo=integer(),
                  mandat=character())


for(x in 1:460){
  okreg <- read_excel(path = 'nowe_jow.xlsx', sheet = x)
  okreg <- left_join(okreg, wyniki, by = 'symbol')
  
  teryt <- as.numeric(substr((okreg$TERYT), 1, 2))
  teryt <- mean(teryt)
  
  konf <- as.numeric(okreg$konf)
  konf <- sum(konf, na.rm = TRUE)
  
  pis <- as.numeric(okreg$pis)
  pis <- sum(pis, na.rm = TRUE)
  
  ko <- as.numeric(okreg$ko)
  ko <- sum(ko, na.rm = TRUE)
  
  emeryci <- as.numeric(okreg$emeryci)
  emeryci <- sum(emeryci, na.rm = TRUE)
  
  niemcy <- as.numeric(okreg$niemcy)
  niemcy <- sum(niemcy, na.rm = TRUE)
  
  psl <- as.numeric(okreg$psl)
  psl <- sum(psl, na.rm = TRUE)

  liroy <- as.numeric(okreg$liroy)
  liroy <- sum(liroy, na.rm = TRUE)
  
  sld <- as.numeric(okreg$sld)
  sld <- sum(sld, na.rm = TRUE)
  
  bis <- as.numeric(okreg$bis)
  bis <- sum(bis, na.rm = TRUE)
  
  prawica <- as.numeric(okreg$prawica)
  prawica <- sum(prawica, na.rm = TRUE)
  
  blok_lewo <- 0.842*sld + 0.5*bis + 0.48*konf + ko + niemcy + emeryci + 0.767*psl
  blok_prawo <- 0.158*sld + pis + prawica + 0.5*bis + 0.52*konf + 0.233*psl + liroy
  
  df2_temp <- data.frame(x, teryt, blok_lewo, blok_prawo, mandat2())
  names(df2_temp) <- c("okreg", "teryt", "blok_lewo", "blok_prawo", "mandat")
  df2 <- rbind(df2, df2_temp)
}

table(df2$mandat)
```

```{r}

# kartogramy dla scenariusza I
mapa <- st_read('wojewodztwa/wojewodztwa.shx')
woj1 <- data.frame(JPT_KOD_JE=integer(),
                  pis=integer(),
                  ko=integer())

for (x in seq(from=2, to =32, by=2)) {
  if (x<10) {
   teryt <- toString(paste("0", x, sep = "")) 
  }else{
    teryt<-toString(x)
  }
  pis <- sum(df1$mandat[df1$teryt==x]=="pis")
  ko <- sum(df1$mandat[df1$teryt==x]=="ko")
  
  woj1_temp <- data.frame(teryt, pis, ko)
  names(woj1_temp) <- c("JPT_KOD_JE", "pis", "ko")
  woj1 <- rbind(woj1, woj1_temp)
}

dane_razem_1 <- left_join(mapa, woj1, by ="JPT_KOD_JE")
dane_razem_1$razem <- dane_razem_1$pis + dane_razem_1$ko
dane_razem_1$ko_proc <- dane_razem_1$ko / dane_razem_1$razem * 100
dane_razem_1$pis_proc <- dane_razem_1$pis / dane_razem_1$razem * 100


png("scenariusz_1_ko.png")
tm_shape(dane_razem_1)+
  tm_layout(legend.format = list(text.separator = "do"),
            legend.text.color = "black",
            legend.text.size = 0.7,
            legend.position = c("left", "bottom"),
            legend.frame = TRUE,
            legend.bg.color = "white")+
  tm_polygons("ko_proc", title="KO [%]", palette="Oranges", midpoint = 100)
dev.off()

png("scenariusz_1_pis.png")
tm_shape(dane_razem_1)+
  tm_layout(legend.format = list(text.separator = "do"),
            legend.text.color = "black",
            legend.text.size = 0.7,
            legend.position = c("left", "bottom"),
            legend.frame = TRUE,
            legend.bg.color = "white")+
    tm_polygons("pis_proc", title="PIS [%]", palette="Blues", midpoint = 0)
dev.off()

```

```{r}
# kartogramy dla scenariusza II

mapa <- st_read('wojewodztwa/wojewodztwa.shx')
woj2 <- data.frame(JPT_KOD_JE=integer(),
                  blok_prawo=integer(),
                  blok_lewo=integer())

for (x in seq(from=2, to =32, by=2)) {
  if (x<10) {
   teryt <- toString(paste("0", x, sep = "")) 
  }else{
    teryt<-toString(x)
  }
  blok_prawo <- sum(df2$mandat[df2$teryt==x]=="blok_prawo")
  blok_lewo <- sum(df2$mandat[df2$teryt==x]=="blok_lewo")
  
  woj2_temp <- data.frame(teryt, blok_prawo, blok_lewo)
  names(woj2_temp) <- c("JPT_KOD_JE", "blok_prawo", "blok_lewo")
  woj2 <- rbind(woj2, woj2_temp)
}

dane_razem_2 <- left_join(mapa, woj2, by ="JPT_KOD_JE")
dane_razem_2$razem <- dane_razem_2$blok_prawo + dane_razem_2$blok_lewo
dane_razem_2$blok_lewo_proc <- dane_razem_2$blok_lewo / dane_razem_2$razem * 100
dane_razem_2$blok_prawo_proc <- dane_razem_2$blok_prawo / dane_razem_2$razem * 100


png("scenariusz_2_ko.png")
tm_shape(dane_razem_2)+
  tm_layout(legend.format = list(text.separator = "do"),
            legend.text.color = "black",
            legend.text.size = 0.7,
            legend.position = c("left", "bottom"),
            legend.frame = TRUE,
            legend.bg.color = "white")+
  tm_polygons("blok_lewo_proc", title="Blok lewicowy [%]", palette="Reds", midpoint = 100)
dev.off()

png("scenariusz_2_pis.png")
tm_shape(dane_razem_2)+
  tm_layout(legend.format = list(text.separator = "do"),
            legend.text.color = "black",
            legend.text.size = 0.7,
            legend.position = c("left", "bottom"),
            legend.frame = TRUE,
            legend.bg.color = "white")+
    tm_polygons("blok_prawo_proc", title="Blok prawicowy [%]", palette="Blues", midpoint = 0)
dev.off()
```


